### ISSUE TITLE
Add or switch to Xenial?

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-travis-lxc#40]
Seems like Xenial is available on Travis:
https://docs.travis-ci.com/user/reference/xenial/

Should I switch this role to support just Xenial and drop Trusty support?

iirc with Xenial we should be able to use LXD easily, maybe, and get rid of many of the patches (like for apt), but I'm not sure if Xenial is actually ready for use (can't find any announcements on the Travis blog).

**Comment by jabl** [comment]
Here's the announcement on the blog: https://blog.travis-ci.com/2018-11-08-xenial-release

**Comment by lae** [comment]
Funny enough, I started experimenting briefly with getting Xenial up 2 days ago while updating my NFS role (having not used LXD much myself yet I'm not too familiar with it, but I did start using it on my Arch desktop earlier this month), but dropped it since I have to focus on prepping for an interview this week. I'll get around to this eventually, but I'd definitely appreciate any help/pointers.

**Comment by lae** [comment]
Closing via #44
